name: energyflex1
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1
  - numpy=1.21.2
  - pandas=1.4.1
  - python=3.9.7
  - pip=21.2.4
  - pyyaml=6.0
  - requests=2.27.1
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - setuptools=58.0.4
  - pytest=6.2.5
  - black=19.10b0
  - sphinx=4.4.0
  - sphinx_rtd_theme=0.4.3
  - pip:
    - causalinference==0.1.3
