################################################################################
# Insert in this file the necessary information to download SPENSER data.
#
################################################################################

spenser_url: "https://osf.io/623qz/download"